version: '2'

services: 
    proxy:
        image: thelastbilly/nginxcontained
        # build: .
        volumes: 
            - "./config.json:/config.json"
            - "./certs:/certs"
            - "./logs:/logs"
        ports:
            - "80:80"
            - "443:443"