version: '2'

services: 
    web:
        image: thelastbilly/nginxcontained
        build: .
        volumes: 
            - "./config.json:/config.json"
            - "./certs:/certs"
        ports:
            - "80:80"
            - "433:433"
        env_file: 
            - "./variables.env"